//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleGeoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Fornitore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Geo_Fornitore()
        {
            this.Geo_UtenteRuolo = new HashSet<Geo_UtenteRuolo>();
            this.Geo_UtenteRuolo1 = new HashSet<Geo_UtenteRuolo>();
        }
    
        public int Id { get; set; }
        public string RagioneSociale { get; set; }
        public string PartitaIva { get; set; }
        public string ContattoTecnico { get; set; }
        public string EmailTecnico { get; set; }
        public string TelefonoTecnico { get; set; }
        public string ContattoTecnico1 { get; set; }
        public string EmailTecnico1 { get; set; }
        public string TelefonoTecnico1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geo_UtenteRuolo> Geo_UtenteRuolo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geo_UtenteRuolo> Geo_UtenteRuolo1 { get; set; }
    }
}
