//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleGeoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_UtenteRuolo
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> IdEnte { get; set; }
        public Nullable<int> IdFornitore { get; set; }
    
        public virtual Geo_Ente Geo_Ente { get; set; }
        public virtual Geo_Ente Geo_Ente1 { get; set; }
        public virtual Geo_Fornitore Geo_Fornitore { get; set; }
        public virtual Geo_Fornitore Geo_Fornitore1 { get; set; }
        public virtual Geo_Ruolo Geo_Ruolo { get; set; }
        public virtual Geo_Utente Geo_Utente { get; set; }
    }
}
