//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuovoPortaleGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Dati
    {
        public long Id { get; set; }
        public string IdUtente { get; set; }
        public string DescrizioneFile { get; set; }
        public string Provincia { get; set; }
        public string Comune { get; set; }
        public string Indirizzo { get; set; }
        public string AltroIndirizzo { get; set; }
        public string Descrizione { get; set; }
        public string Cap { get; set; }
        public string Approx01 { get; set; }
        public string Approx02 { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public Nullable<bool> OpenStreetMap { get; set; }
        public Nullable<bool> Here { get; set; }
        public Nullable<bool> Google { get; set; }
        public string Here_MatchLevel { get; set; }
        public string Here_MatchType { get; set; }
        public string Here_Relevance { get; set; }
        public string Here_Error { get; set; }
    
        public virtual Geo_Utente Geo_Utente { get; set; }
    }
}
