//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleGeoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Attività
    {
        public int IdGeo { get; set; }
        public string Autore { get; set; }
        public string DescrizioneFile { get; set; }
        public string PathFile { get; set; }
        public Nullable<bool> Here { get; set; }
        public Nullable<bool> OpenStreetMap { get; set; }
        public string Id_Autore { get; set; }
    
        public virtual Geo_Utente Geo_Utente { get; set; }
    }
}
