//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleGeoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Ente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Geo_Ente()
        {
            this.Geo_UtenteRuolo = new HashSet<Geo_UtenteRuolo>();
            this.Geo_UtenteRuolo1 = new HashSet<Geo_UtenteRuolo>();
        }
    
        public int Id { get; set; }
        public string CodiceIstat { get; set; }
        public string CodiceFisco { get; set; }
        public string SiglaProv { get; set; }
        public string Cap { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> ValidoDal { get; set; }
        public Nullable<System.DateTime> ValidoAl { get; set; }
        public Nullable<int> AderisceDigipalm { get; set; }
        public Nullable<int> OnBoardingRicevuto { get; set; }
        public Nullable<int> OnBoardingInviato { get; set; }
        public string CodiceFiscale { get; set; }
        public Nullable<int> PraticheUSR { get; set; }
        public string AuthIoWS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geo_UtenteRuolo> Geo_UtenteRuolo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geo_UtenteRuolo> Geo_UtenteRuolo1 { get; set; }
    }
}
