//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuovoPortaleGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_UtenteRuolo
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
    
        public virtual Geo_Ruolo Geo_Ruolo { get; set; }
        public virtual Geo_Utente Geo_Utente { get; set; }
    }
}
