//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuovoPortaleGeo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeoCodeEntities1 : DbContext
    {
        public GeoCodeEntities1()
            : base("name=GeoCodeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Geo_Utente> Geo_Utente { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<OpenStreetMapCSV> OpenStreetMapCSV { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Geo_Ruolo> Geo_Ruolo { get; set; }
        public virtual DbSet<Geo_UtenteRuolo> Geo_UtenteRuolo { get; set; }
        public virtual DbSet<Geo_Dati> Geo_Dati { get; set; }
        public virtual DbSet<Geo_Attività> Geo_Attività { get; set; }
    }
}
