//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuovoPortaleGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenStreetMapCSV
    {
        public int Id { get; set; }
        public string Indirizzo { get; set; }
        public string N_Civico { get; set; }
        public string Comune { get; set; }
        public string IstatComune { get; set; }
        public string Provincia { get; set; }
        public string IstatProvincia { get; set; }
        public string Regione { get; set; }
        public string IstatRegione { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string Approx01 { get; set; }
        public string Approx02 { get; set; }
        public string Cap { get; set; }
        public string AltroIndirizzo { get; set; }
        public string APIGoogle { get; set; }
    }
}
