GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC;


GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC;


GO
GRANT CONNECT TO [REGIONEMARCHE\Luca_silvestrini];


GO
GRANT CONNECT TO [REGIONEMARCHE\Mirco_Sturari];


GO
GRANT CONNECT TO [REGIONEMARCHE\Giacomo_Fiorentini];


GO
GRANT CONNECT TO [ut_IntraGeoRef];

